// Mocks generated by Mockito 5.1.0 from annotations
// in contacts_data/test/home_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:contacts_data/bloc/contact_bloc.dart' as _i3;
import 'package:contacts_data/model/contact.dart' as _i5;
import 'package:contacts_data/repository/repository_interface_contact.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeRepositoryInterfaceContact_0 extends _i1.Fake
    implements _i2.RepositoryInterfaceContact {}

/// A class which mocks [ContactBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockContactBloc extends _i1.Mock implements _i3.ContactBloc {
  MockContactBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RepositoryInterfaceContact get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
              returnValue: _FakeRepositoryInterfaceContact_0())
          as _i2.RepositoryInterfaceContact);
  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(Invocation.method(#initialize, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  _i4.Future<List<_i5.Contact>> getContacts() =>
      (super.noSuchMethod(Invocation.method(#getContacts, []),
              returnValue: Future<List<_i5.Contact>>.value(<_i5.Contact>[]))
          as _i4.Future<List<_i5.Contact>>);
}
